package com.example.moviesapp

import androidx.lifecycle.ViewModel

class FilmViewModel : ViewModel() {
    val filmList = listOf<Film>(
        Film(
            R.string.id,
            R.string.film_name,
            R.drawable.the_shining,
            R.string.date,
            R.string.rating,
            R.string.film_description
        ),
        Film(
            R.string.id,
            R.string.film_name,
            R.drawable.the_shining,
            R.string.date,
            R.string.rating,
            R.string.film_description
        ),
        Film(
            R.string.id,
            R.string.film_name,
            R.drawable.the_shining,
            R.string.date,
            R.string.rating,
            R.string.film_description
        ),
        Film(
            R.string.id,
            R.string.film_name,
            R.drawable.the_shining,
            R.string.date,
            R.string.rating,
            R.string.film_description
        ),
        Film(
            R.string.id,
            R.string.film_name,
            R.drawable.the_shining,
            R.string.date,
            R.string.rating,
            R.string.film_description
        ),
        Film(
            R.string.id,
            R.string.film_name,
            R.drawable.the_shining,
            R.string.date,
            R.string.rating,
            R.string.film_description
        ),
        Film(
            R.string.id,
            R.string.film_name,
            R.drawable.the_shining,
            R.string.date,
            R.string.rating,
            R.string.film_description
        ),
        Film(
            R.string.id,
            R.string.film_name,
            R.drawable.the_shining,
            R.string.date,
            R.string.rating,
            R.string.film_description
        ),
        Film(
            R.string.id,
            R.string.film_name,
            R.drawable.the_shining,
            R.string.date,
            R.string.rating,
            R.string.film_description
        ),
        Film(
            R.string.id,
            R.string.film_name,
            R.drawable.the_shining,
            R.string.date,
            R.string.rating,
            R.string.film_description
        ),
        Film(
            R.string.id,
            R.string.film_name,
            R.drawable.the_shining,
            R.string.date,
            R.string.rating,
            R.string.film_description
        ),
        Film(
            R.string.id,
            R.string.film_name,
            R.drawable.the_shining,
            R.string.date,
            R.string.rating,
            R.string.film_description
        ),
        Film(
            R.string.id,
            R.string.film_name,
            R.drawable.the_shining,
            R.string.date,
            R.string.rating,
            R.string.film_description
        ),
        Film(
            R.string.id,
            R.string.film_name,
            R.drawable.the_shining,
            R.string.date,
            R.string.rating,
            R.string.film_description
        ),
        Film(
            R.string.id,
            R.string.film_name,
            R.drawable.the_shining,
            R.string.date,
            R.string.rating,
            R.string.film_description
        ),
        Film(
            R.string.id,
            R.string.film_name,
            R.drawable.the_shining,
            R.string.date,
            R.string.rating,
            R.string.film_description
        ),
        Film(
            R.string.id,
            R.string.film_name,
            R.drawable.the_shining,
            R.string.date,
            R.string.rating,
            R.string.film_description
        )
    )


}